config/routes.rb
Searchabook::Application.routes.draw do  
  resources :nonfictionliteraturecategories

  resources :educationliteraturecategories

  resources :educationliteratures

  resources :nonfictionliteratures

  resources :booksalecategories

  resources :booksales

  resources :businesscategories

  resources :businessbooks

  resources :kidandparentcategories

  resources :kidandparentbooks

  get "sessions/new"

  resources :users

  resources :categories

  resources :books
  
  resources :sessions
  
  get 'signup', :to => 'users#new', :as  => 'signup'
  get 'login', :to  => 'sessions#new', :as  => 'login'
  get 'logout', :to  => 'sessions#destroy', :as =>  'logout'

  root :to => 'books#index'

end

app/models/educationliterature.rb
class Educationliterature < ActiveRecord::Base
  attr_accessible :author, :category, :description, :link, :picture, :price, :publisher, :title, :vendor, :year
  
      def self.search(search)
    if search
      search = search.downcase
      where('LOWER(title) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/educationliteratures_controller.rb
class EducationliteraturesController < ApplicationController

before_filter :authorize, :only => [:new, :edit, :update, :destroy]
  
  # GET /educationliteratures
  # GET /educationliteratures.json
  def index
    @educationliteratures = Educationliterature.search(params[:search]).paginate(:per_page => 18, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @educationliteratures }
    end
  end

  # GET /educationliteratures/1
  # GET /educationliteratures/1.json
  def show
    @educationliterature = Educationliterature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @educationliterature }
    end
  end

  # GET /educationliteratures/new
  # GET /educationliteratures/new.json
  def new
    @educationliterature = Educationliterature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @educationliterature }
    end
  end

  # GET /educationliteratures/1/edit
  def edit
    @educationliterature = Educationliterature.find(params[:id])
  end

  # POST /educationliteratures
  # POST /educationliteratures.json
  def create
    @educationliterature = Educationliterature.new(params[:educationliterature])

    respond_to do |format|
      if @educationliterature.save
        format.html { redirect_to @educationliterature, :notice => 'Educationliterature was successfully created.' }
        format.json { render :json => @educationliterature, :status => :created, :location => @educationliterature }
      else
        format.html { render :action => "new" }
        format.json { render :json => @educationliterature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /educationliteratures/1
  # PUT /educationliteratures/1.json
  def update
    @educationliterature = Educationliterature.find(params[:id])

    respond_to do |format|
      if @educationliterature.update_attributes(params[:educationliterature])
        format.html { redirect_to @educationliterature, :notice => 'Educationliterature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @educationliterature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /educationliteratures/1
  # DELETE /educationliteratures/1.json
  def destroy
    @educationliterature = Educationliterature.find(params[:id])
    @educationliterature.destroy

    respond_to do |format|
      format.html { redirect_to educationliteratures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/educationliteratures_helper.rb
module EducationliteraturesHelper
end

app/views/educationliteratures/_form.html.erb
<%= form_for(@educationliterature) do |f| %>
  <% if @educationliterature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@educationliterature.errors.count, "error") %> prohibited this educationliterature from being saved:</h2>

      <ul>
      <% @educationliterature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :vendor %><br />
    <%= f.text_field :vendor %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educationliteratures/_products.html.erb
<table class="table table-striped">
<% @educationliteratures.each do |educationliterature| %>
	<tr><td colspan="3">

<script type="text/javascript"><!--
google_ad_client = "ca-pub-7167913289158306";
/* 728x15, создано 02.05.09 */
google_ad_slot = "1888275628";
google_ad_width = 728;
google_ad_height = 15;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
		
	</td></tr>

  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td>
      <%= link_to( image_tag(educationliterature.picture, :class => 'list_image'), educationliterature.link) %>
    </td>

    <td class="list_description">
      <dl>
        <dt><h2><%= link_to(educationliterature.title, educationliterature.link, :class => "green") %></h2></dt>
        <dd><%= truncate(strip_tags(educationliterature.description),
               :length => 300) %></dd>
        <dd><h3>Цена: <%= educationliterature.price %></h3></dd>
      </dl>

    </td>

    <td class="list_actions">
      <%= link_to("Подробнее", educationliterature.link, :class => "btn btn-info") %>

            
      <% if current_user %>
      <%= link_to 'Просмотр', educationliterature %><br/>
      <%= link_to 'Редактирование', edit_educationliterature_path(book) %><br/>
      <%= link_to 'Удаление', educationliterature, 
                  :confirm => 'Вы уверены?',
                  :method => :delete %>
      <% end %>


    </td>
  </tr>

<% end %>
</table>

app/views/educationliteratures/_sidebar.html.erb
<div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Каталог</li>
			<%  @educationliteraturecategories = Educationliteraturecategory.all %>
              <% @educationliteraturecategories.each do |educationliteraturecategory| %>

              <li><%= link_to educationliteratureategory.name, "/educationliteratures/?utf8=✓&search=#{educationliteraturecategory.name}" %></li>

              <% end %>
            </ul>
          </div><!--/.well -->

        </div><!--/span-->
        

app/views/educationliteratures/edit.html.erb
<h1>Editing educationliterature</h1>

<%= render 'form' %>

<%= link_to 'Show', @educationliterature %> |
<%= link_to 'Back', educationliteratures_path %>

app/views/educationliteratures/index.html.erb
      <%= render 'sidebar' %>
<div class="span9">

<div id="products"><%= render 'products' %></div>


<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @educationliteratures %>
    </div>
    <%= will_paginate @educationliteratures, :container => false %>
  </div>
<br />
      <% if current_user %>
<%= link_to 'New Book', new_educationliterature_path %>
<% end %>
</div>

app/views/educationliteratures/new.html.erb
<h1>New educationliterature</h1>

<%= render 'form' %>

<%= link_to 'Back', educationliteratures_path %>

app/views/educationliteratures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @educationliterature.title %>
</p>

<p>
  <b>Description:</b>
  <%= @educationliterature.description %>
</p>

<p>
  <b>Link:</b>
  <%= @educationliterature.link %>
</p>

<p>
  <b>Price:</b>
  <%= @educationliterature.price %>
</p>

<p>
  <b>Publisher:</b>
  <%= @educationliterature.publisher %>
</p>

<p>
  <b>Year:</b>
  <%= @educationliterature.year %>
</p>

<p>
  <b>Vendor:</b>
  <%= @educationliterature.vendor %>
</p>

<p>
  <b>Picture:</b>
  <%= @educationliterature.picture %>
</p>

<p>
  <b>Category:</b>
  <%= @educationliterature.category %>
</p>

<p>
  <b>Author:</b>
  <%= @educationliterature.author %>
</p>


<%= link_to 'Edit', edit_educationliterature_path(@educationliterature) %> |
<%= link_to 'Back', educationliteratures_path %>