config/routes.rb
Searchabook::Application.routes.draw do  
  resources :nonfictionliteraturecategories

  resources :educationliteraturecategories

  resources :educationliteratures

  resources :nonfictionliteratures

  resources :booksalecategories

  resources :booksales

  resources :businesscategories

  resources :businessbooks

  resources :kidandparentcategories

  resources :kidandparentbooks

  get "sessions/new"

  resources :users

  resources :categories

  resources :books
  
  resources :sessions
  
  get 'signup', :to => 'users#new', :as  => 'signup'
  get 'login', :to  => 'sessions#new', :as  => 'login'
  get 'logout', :to  => 'sessions#destroy', :as =>  'logout'

  root :to => 'books#index'

end

app/models/booksalecategory.rb
class Booksalecategory < ActiveRecord::Base
  attr_accessible :category, :name, :parentcategoryid
end

app/controllers/booksalecategories_controller.rb
class BooksalecategoriesController < ApplicationController
  # GET /booksalecategories
  # GET /booksalecategories.json
  def index
    @booksalecategories = Booksalecategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @booksalecategories }
    end
  end

  # GET /booksalecategories/1
  # GET /booksalecategories/1.json
  def show
    @booksalecategory = Booksalecategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @booksalecategory }
    end
  end

  # GET /booksalecategories/new
  # GET /booksalecategories/new.json
  def new
    @booksalecategory = Booksalecategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @booksalecategory }
    end
  end

  # GET /booksalecategories/1/edit
  def edit
    @booksalecategory = Booksalecategory.find(params[:id])
  end

  # POST /booksalecategories
  # POST /booksalecategories.json
  def create
    @booksalecategory = Booksalecategory.new(params[:booksalecategory])

    respond_to do |format|
      if @booksalecategory.save
        format.html { redirect_to @booksalecategory, :notice => 'Booksalecategory was successfully created.' }
        format.json { render :json => @booksalecategory, :status => :created, :location => @booksalecategory }
      else
        format.html { render :action => "new" }
        format.json { render :json => @booksalecategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /booksalecategories/1
  # PUT /booksalecategories/1.json
  def update
    @booksalecategory = Booksalecategory.find(params[:id])

    respond_to do |format|
      if @booksalecategory.update_attributes(params[:booksalecategory])
        format.html { redirect_to @booksalecategory, :notice => 'Booksalecategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @booksalecategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /booksalecategories/1
  # DELETE /booksalecategories/1.json
  def destroy
    @booksalecategory = Booksalecategory.find(params[:id])
    @booksalecategory.destroy

    respond_to do |format|
      format.html { redirect_to booksalecategories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/booksalecategories_helper.rb
module BooksalecategoriesHelper
end

app/views/booksalecategories/_form.html.erb
<%= form_for(@booksalecategory) do |f| %>
  <% if @booksalecategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booksalecategory.errors.count, "error") %> prohibited this booksalecategory from being saved:</h2>

      <ul>
      <% @booksalecategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :parentcategoryid %><br />
    <%= f.text_field :parentcategoryid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/booksalecategories/edit.html.erb
<h1>Editing booksalecategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @booksalecategory %> |
<%= link_to 'Back', booksalecategories_path %>

app/views/booksalecategories/index.html.erb
<h1>Listing booksalecategories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Parentcategoryid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @booksalecategories.each do |booksalecategory| %>
  <tr>
    <td><%= booksalecategory.name %></td>
    <td><%= booksalecategory.category %></td>
    <td><%= booksalecategory.parentcategoryid %></td>
    <td><%= link_to 'Show', booksalecategory %></td>
    <td><%= link_to 'Edit', edit_booksalecategory_path(booksalecategory) %></td>
    <td><%= link_to 'Destroy', booksalecategory, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booksalecategory', new_booksalecategory_path %>

app/views/booksalecategories/new.html.erb
<h1>New booksalecategory</h1>

<%= render 'form' %>

<%= link_to 'Back', booksalecategories_path %>

app/views/booksalecategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @booksalecategory.name %>
</p>

<p>
  <b>Category:</b>
  <%= @booksalecategory.category %>
</p>

<p>
  <b>Parentcategoryid:</b>
  <%= @booksalecategory.parentcategoryid %>
</p>


<%= link_to 'Edit', edit_booksalecategory_path(@booksalecategory) %> |
<%= link_to 'Back', booksalecategories_path %>