config/routes.rb
Searchabook::Application.routes.draw do  
  resources :nonfictionliteraturecategories

  resources :educationliteraturecategories

  resources :educationliteratures

  resources :nonfictionliteratures

  resources :booksalecategories

  resources :booksales

  resources :businesscategories

  resources :businessbooks

  resources :kidandparentcategories

  resources :kidandparentbooks

  get "sessions/new"

  resources :users

  resources :categories

  resources :books
  
  resources :sessions
  
  get 'signup', :to => 'users#new', :as  => 'signup'
  get 'login', :to  => 'sessions#new', :as  => 'login'
  get 'logout', :to  => 'sessions#destroy', :as =>  'logout'

  root :to => 'books#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :categoryid, :name, :parentcategoryid, :theme
  
    def self.search(search)
    if search
      search = search.downcase
      where('LOWER(name) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_filter :authorize, :only => [:edit, :update, :destroy]
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.search(params[:search]).paginate(:per_page => 10, :page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :categoryid %><br />
    <%= f.number_field :categoryid %>
  </div>
  <div class="field">
    <%= f.label :parentcategoryid %><br />
    <%= f.number_field :parentcategoryid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="span8">
<h1>Listing categories</h1>

<%= form_tag books_path, :method => 'get', :id => "categories_search" do %>

  <p>
    <%= text_field_tag :search, params[:search], :id => "keyword" %>
    <%= submit_tag "Искать", :name => nil %>
  </p>
<% end %>







<table>
  <tr>
    <th>Name</th>
    <th>Categoryid</th>
    <th>Parentcategoryid</th>
        <th>Theme</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.categoryid %></td>
    <td><%= category.parentcategoryid %></td>
    <td><%= category.theme %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @categories %>
    </div>
    <%= will_paginate @categories, :container => false %>
  </div>
<br />

<%= link_to 'New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Categoryid:</b>
  <%= @category.categoryid %>
</p>

<p>
  <b>Parentcategoryid:</b>
  <%= @category.parentcategoryid %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>