config/routes.rb
Searchabook::Application.routes.draw do  
  resources :nonfictionliteraturecategories

  resources :educationliteraturecategories

  resources :educationliteratures

  resources :nonfictionliteratures

  resources :booksalecategories

  resources :booksales

  resources :businesscategories

  resources :businessbooks

  resources :kidandparentcategories

  resources :kidandparentbooks

  get "sessions/new"

  resources :users

  resources :categories

  resources :books
  
  resources :sessions
  
  get 'signup', :to => 'users#new', :as  => 'signup'
  get 'login', :to  => 'sessions#new', :as  => 'login'
  get 'logout', :to  => 'sessions#destroy', :as =>  'logout'

  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :category, :description, :picture, :price, :publisher, :title, :vendor, :year, :link
  
    def self.search(search)
    if search
      search = search.downcase
      where('LOWER(title) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
  
end

app/models/booksale.rb
class Booksale < ActiveRecord::Base
  attr_accessible :author, :category, :description, :link, :picture, :price, :publisher, :title, :vendor, :year
  
  def self.search(search)
    if search
      search = search.downcase
      where('LOWER(title) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
end

app/models/booksalecategory.rb
class Booksalecategory < ActiveRecord::Base
  attr_accessible :category, :name, :parentcategoryid
end

app/models/businessbook.rb
class Businessbook < ActiveRecord::Base
  attr_accessible :author, :category, :description, :link, :picture, :price, :publisher, :title, :vendor, :year
  
      def self.search(search)
    if search
      search = search.downcase
      where('LOWER(title) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/businesscategory.rb
class Businesscategory < ActiveRecord::Base
  attr_accessible :category, :name, :parentcategoryid
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :categoryid, :name, :parentcategoryid, :theme
  
    def self.search(search)
    if search
      search = search.downcase
      where('LOWER(name) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
end

app/models/educationliterature.rb
class Educationliterature < ActiveRecord::Base
  attr_accessible :author, :category, :description, :link, :picture, :price, :publisher, :title, :vendor, :year
  
      def self.search(search)
    if search
      search = search.downcase
      where('LOWER(title) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/kidandparentbook.rb
class Kidandparentbook < ActiveRecord::Base
  attr_accessible :author, :category, :description, :link, :picture, :price, :publisher, :title, :vendor, :year
  
      def self.search(search)
    if search
      search = search.downcase
      where('LOWER(title) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
end

app/models/kidandparentcategory.rb
class Kidandparentcategory < ActiveRecord::Base
  attr_accessible :categoryid, :name, :parentcategoryid
end

app/models/nonfictionliterature.rb
class Nonfictionliterature < ActiveRecord::Base
  attr_accessible :author, :category, :description, :link, :picture, :price, :publisher, :title, :vendor, :year
  
      def self.search(search)
    if search
      search = search.downcase
      where('LOWER(title) LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :password, :password_confirmation
  validates_uniqueness_of :email
  has_secure_password
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_filter :authorize, :only => [:new, :edit, :update, :destroy]
  
  # GET /books
  # GET /books.json
  def index
    @books = Book.search(params[:search]).paginate(:per_page => 3, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @book }
    end
  end
  
  # GET /books/1
  # GET /books/1.json
  def showcategory
    
    @book = Book.find(params[:category]).paginate(:per_page => 5, :page => params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @book }
    end
  end  

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, :notice => 'Book was successfully created.' }
        format.json { render :json => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, :notice => 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authorize, :only => [:create, :new]
  
    def new
    @user = User.new
  end
  
  def create
  @user = User.new(params[:user])
  if @user.save
    session[:user_id] = @user.id
    redirect_to root_url, :notice => "Thank you for signing up!"
  else
    render "new"
  end
  end
  
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  
  def sortable(column, title = nil)
    
    title ||= column.titleize
    css_class = (column == sort_column) ? "#{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" :  "asc"
#    title = sort_direction == "asc" ?  title : title + "▲"
#    title = sort_direction == "desc" ? title : title + "▼"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
   
    
  end

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Search a book online service"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/booksales_helper.rb
module BooksalesHelper
end

app/helpers/businessbooks_helper.rb
module BusinessbooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="span12">
  <small>
    <a href="http://moloko.ws/">Software Development</a>
    by Dmitri E. Molokov
  </small>
  <nav>
    <ul>
					<li>
						<%= link_to "Электронные книги",    books_path %>
					</li>
					<li>
						<%= link_to "Для детей и родителей",    kidandparentbooks_path %>
					</li>
					<li>
						<%= link_to "Книги о бизнесе и для бизнеса",    businessbooks_path %>
					</li>
					<li>
						<%= link_to "Специальная литература",    nonfictionliteratures_path %>
					</li>
					
					
  <% if current_user %>
  	<li><%= link_to "Категории",    categories_path %></li>
    <li><%= link_to "Logged in as #{current_user.email}", root_path %></li>
    <li><%= link_to "Log Out", logout_path %></li>
    <li><%= link_to "Sign Up", signup_path %></li>
  <% else %>
    
    <li><%= link_to "Log In", login_path %></li>
   <% end %>
    </ul>
  </nav>
  </div>
  <!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter16113466 = new Ya.Metrika({id:16113466, enableAll: true});
        } catch(e) {}
    });
    
    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/16113466" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
			<a class="brand" href="#">Поиск электронных книг</a>
			<div class="btn-group pull-right">
				<% if current_user %>
				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#"> <i class="icon-user"></i> <% current_user.email %> <span class="caret"></span> </a>

				<ul class="dropdown-menu">
					<li>
						<%= link_to "Профиль", login_path %>
					</li>
					<li>
						<%= link_to "Регистрация", signup_path %>
					</li>
					<li class="divider"></li>
					<li>
						<%= link_to "Выход", logout_path %>
					</li>
				</ul>
				<% else %>
				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#"> 
					<i class="icon-user"></i> Вход <span class="caret"></span> </a>

				<ul class="dropdown-menu">
					<li>
						<%= link_to "Войти", login_path %>
					</li>
					<li>
						<%= link_to "Регистрация", signup_path %>
					</li>
					<li class="divider"></li>
				</ul>

				<% end %>
			</div>

			<div class="nav-collapse">
				<ul class="nav">

					<li>
						<%= link_to "Электронные книги",    books_path %>
					</li>
					<li>
						<%= link_to "Для детей и родителей",    kidandparentbooks_path %>
					</li>
					<li>
						<%= link_to "Книги о бизнесе и для бизнеса",    businessbooks_path %>
					</li>
					<li>
						<%= link_to "Специальная литература",    nonfictionliteratures_path %>
					</li>

				</ul>
			</div><!--/.nav-collapse -->

		</div>
</header>

app/views/layouts/_products.html.erb
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-striped">
<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td>
      <%= image_tag(product.image_url, :class => 'list_image') %>
    </td>

    <td class="list_description">
      <dl>
        <dt><%= product.title %></dt>
        <dd><%= truncate(strip_tags(product.description),
               length: 80) %></dd>
        <dd>Цена: <%= product.price %></dd>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Просмотр', product %><br/>
      <%= link_to 'Редактирование', edit_product_path(product) %><br/>
      <%= link_to 'Удаление', product, 
                  confirm: 'Вы уверены?',
                  method: :delete %>
    </td>
  </tr>
<% end %>
</table>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Каталог</li>
			<%  @categories = Category.all %>
              <% @categories.each do |category| %>

              <li><%= link_to category.name, "/books/?utf8=✓&search=#{category.name}" %></li>

              <% end %>
            </ul>
          </div><!--/.well -->

        </div><!--/span-->
        


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media =>"all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container-fluid">
      <div class="row-fluid">
      	<div class="span12">
<%= form_tag books_path, :method => 'get', :id => "books_search", :class => "well form-search" do %>

  <p>
    <%= text_field_tag :search, params[:search], :id => "keyword", :class => "input-large search-query" %>
    <%= submit_tag "Искать", :name => nil, :class => "btn btn-success" %>
  </p>
<% end %>
</div></div>
<div class="row-fluid">

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div></div> 

  </body>
</html>